### ISSUE TITLE
Um..... There is so DiscordSelfBot.jar (REDACTED CUS I WAS STUPID SORRY)

### ISSUE THREAD

**Issue by jdhydra** [Fabricio20/DiscordSelfBot#1]
YEAH......
![image](https://cloud.githubusercontent.com/assets/16177268/17088914/27b4fe56-51ef-11e6-8442-4e9d9b36945a.png)

**Comment by Fabricio20** [comment]
I think you should open up the [releases ](https://github.com/Fabricio20/DiscordSelfBot/releases)section lol.

Though I don't remember if this works, been some time since I last touched this, if you have any major problems make an issue here and I'll try to fix them as soon as JDA-Client is working again.
