### ISSUE TITLE
Steals email and password?!

### ISSUE THREAD

**Issue by Silverarmor** [Fabricio20/DiscordSelfBot#8]
I have used 18 self bots in my time, and they ALL use a token to login.

Using email and password **Won't work** because 
A: I have 2 factor authentication
B:  Quoted from a github dev post:
`Self bots aren't supported. You shouldn't be going through the 2FA login flow on your bot either. Log in on the client, grab the token from local storage and use that token in your self bot.
Do not call /api/login or /api/auth/mfa/totp.
I repeat. Do not call /api/login or /api/auth/mfa/totp. If you are using a self bot on a 2fa enabled account, and you are automating the login and mfa flow. Your account will get banned. Instead, log in on the discord client, pop open the web inspector, (ctrl/cmd shift I), and type localStorage.token in the console to get your auth token. Pass this to the bot library instead, like you would a bot token. discord.py supports this as client.run('mfa.theTokenHere', bot=False). Do NOT automate calling /api/login. and /api/auth/mfa/totp Your account will get banned.`

So, I _could_ Report you but i might.

Thanks.

**Comment by Fabricio20** [comment]
First off, no this won't steal your password, there's a reason this is open source.

Second, if you look at the date this was published you will notice that it happened when the token "wasn't still a thing" and that the automated account login wasn't "banned" yet.

Third, this is a non-functional selfbot since it hasn't been updated for a long time and the api utilized here (JDA 2.X) has been discontinued. (Read #5 #6 #7).

And fourth, feel free to report me as I'm not advertising this anywhere nor endorsing it's usage, I simply put the code on github for easy of storage.

**Comment by DV8FromTheWorld** [comment]
It even shows exactly what is being done with the username and password:
https://github.com/Fabricio20/DiscordSelfBot/blob/master/src/main/java/net/notfab/discord/selfbot/Main.java#L36

Which is reference to this in JDA 1.4: https://github.com/DV8FromTheWorld/JDA/blob/63039da89ce86d677addb069d9c07cf3ccdc3ecc/src/main/java/net/dv8tion/jda/JDABuilder.java#L77

Which then provides the username and password to:
https://github.com/DV8FromTheWorld/JDA/blob/63039da89ce86d677addb069d9c07cf3ccdc3ecc/src/main/java/net/dv8tion/jda/entities/impl/JDAImpl.java#L133

Which logs into the discord API.

Instead of riding high on your high horse, how about research a bit, especially since there are 3 other issues dealing with this and this project and its dependencies are completely open source.
